### ISSUE TITLE
Using the rust benchmark instead of nodejs benchmark

### ISSUE THREAD

**Issue by IWANABETHATGUY** [speedy-js/rspack-sources#12]
https://github.com/speedy-js/rspack/pull/477

**Comment by h-a-n-a** [comment]
closed as resolved in https://github.com/speedy-js/rspack-sources/pull/16

**Comment by IWANABETHATGUY** [comment]
https://github.com/speedy-js/rspack-sources/commit/77d131e419ac4e5fccbf48aed15d150151374a32#comments
According to this commit. comment, I don't this benchmark action is preferable.
